files:
  -
    source: '/init_docs/languages/test.txt
    translation: '/init_docs/languages/%locale%.txt
    languages_mapping:
      locale:
        'ar-SA': 'Arabic.txt'
        'es-ES': 'Spanish.txt'
        'ur-PK': 'Urdu.txt'
